pref("extensions.webannotator.savecolors", false);
pref("extensions.webannotator.activatelinks", true);
pref("extensions.webannotator.saveformat", "only_html");
pref("extensions.webannotator.quitAfterSave", true);
pref("extensions.webannotator.autoExport", false);
pref("extensions.webannotator.showTitlePopup", false);
pref("extensions.webannotator.namingStrategy", "numbers");
pref("extensions.webannotator.editIconsShowDelay", 100);
pref("extensions.webannotator.editIconsHideDelay", 500);
